config/routes.rb
Cartem::Application.routes.draw do
  resources :companies

  devise_for :users, :controllers => {
    :sessions  => "admin/sessions",
    :passwords => "admin/passwords"
  }
  

  namespace :admin do

    root :to => "dashboard#index"

    resources :companies
    
    resources :categories
    resources :users, :except => [:show]
    
  end

  root :to => 'pages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessible :name, :parent_id

  validates_presence_of :name

  acts_as_nested_set

  has_many :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :category
  attr_accessible :address, :description, :email, :name, :website, :category_id, :phone
  
  validates_presence_of :name, :address, :phone
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  validates_associated :category
  
  scope :in_categories, lambda { |categories|
    where(:category_id => categories)  # accepts one or an array of either integers or Categories
  }
  
  scope :search, lambda { |terms| 
     where("title LIKE :t OR body LIKE :t", :t => "%#{terms}%")
  }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController

  before_filter :load_resources, :only => [:new, :create, :edit, :update] 

  def index
    @categories = Category.all
    respond_with @categories
  end

  def show
    @category = Category.find(params[:id])
    respond_with @category
  end

  def new
    @category = Category.new
    respond_with @category
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    flash[:notice] = "Categoria Adicionada." if @category.save
    respond_with @category, :location => admin_categories_path

  end

  def update
    @category = Category.find(params[:id])
    flash[:notice] ="Categoria Atualizada." if @category. update_attributes(params[:category])
    respond_with @category, :location => admin_categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_with @category, :location => admin_categories_path
  end

  protected
    def load_resources
      @categories = Category.all
    end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminController
  
  before_filter :load_resources, :only => [:new, :create, :edit, :update] 
  
  def index
    @companies = Company.paginate(:page => params[:page])
    respond_with @companies
  end

  def show
    @company = Company.find(params[:id])
    respond_with @company
  end

  def new

    @company = Company.new
    respond_with @company

  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(params[:company])
    flash[:notice] = 'Empresa Adicionada' if @company.save
    respond_with @company, :location => admin_companies_path()
  end

  def update
    @company = Company.find(params[:id])
    flash[:notice] = 'Empresa Atualizada.' if @company.update_attributes(params[:company])
    respond_with @company, :location => admin_companies_path
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    respond_with @company, :location => admin_companies_path
  end

protected
  def load_resources
    @categories = Category.all
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController

  def index
    
  end

end

app/controllers/admin/passwords_controller.rb
class Admin::PasswordsController < Devise::PasswordsController
  layout "admin"
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :html, :xml, :json

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  include NavLinkHelper
  
  before_filter :load_resources, :only => [:index]
  
  def index
    @companies = Company.scoped
    @companies = @companies.in_categories(@category_root.descendants) if @category_root.present?
    @companies = @category.companies if @category.present?
    @companies = @companies.paginate(:page => params[:page], :per_page => 5) 
    #maybe the above is wrong because we already have made the search and so its doing a repeated
    # retrieve on database, now if I put it on Company.scoped.paginate it doesn't work with
    # params[:category_id]
    respond_with @companies
  end

  def show
    @company = Company.find(params[:id])
    respond_with @company
  end

  def load_resources
    # do it better
    @category_root = Category.find(params[:category_root]) if params[:category_root]
    @category = Category.find(params[:category_id]) if params[:category_id]
    @category_roots = Category.roots

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @category_roots = Category.roots    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(resource)
    render "shared/error_messages", :resource => resource
  end

  def flash_messages
    flash.collect do |key, msg|
      content_tag :div, msg, :id => key, :class => "alert"
    end.join.html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/nav_link_helper.rb
module NavLinkHelper

  def nav_link(title, path, html_options = {}, options = {})
    LinkGenerator.new(request, title, path, html_options, options).to_html
  end

  class LinkGenerator
    include ActionView::Helpers::UrlHelper

    def initialize(request, title, path, html_options = {}, options = {})
      @request      = request
      @title        = title
      @path         = path
      @html_options = html_options
      @options      = options
    end

    def to_html
      html = link

      if @options[:wrapper]
        html = content_tag(@options[:wrapper], html, :class => wrapper_classes)
      end

      html.html_safe
    end

    private

    def current_path
      comparable_path_for(@request.fullpath)
    end

    def link_path
      comparable_path_for(url_for(@path))
    end

    def segment_position
      if @options[:controller_segment]
        @options[:controller_segment] - 1
      elsif @options[:url_segment]
        @options[:url_segment]
      end
    end

    def path_controller
      controller_for(@path)
    end

    def current_controller
      controller_for(@request.path)
    end

    def segment_for(controller, path)
      if @options[:controller_segment]
        controller.split('/')[segment_position]
      elsif @options[:url_segment]
        path.split('/')[segment_position]
      end
    end

    def path_segment
      segment_for(path_controller, current_path)
    end

    def current_segment
      segment_for(current_controller, link_path)
    end

    def paths_match?
      current_path == link_path
    end

    def segments_match?
      path_segment && path_segment == current_segment
    end

    def selected?
      paths_match? || segments_match?
    end

    def selected_class
      @options[:selected_class] || 'selected'
    end

    def link_classes
      if @html_options[:class]
        @html_options[:class] + " #{selected_class}"
      else
        selected_class
      end
    end

    def html_options
      selected? ? @html_options.merge(:class => link_classes) : @html_options
    end

    def link
      link_to(@title, @path, html_options)
    end

    def wrapper_classes
      if selected?
        "#{selected_class} #{@options[:wrapper_class]}"
      else
        @options[:wrapper_class]
      end
    end

    def controller_for(path)
      Rails.application.routes.recognize_path(path)[:controller]
    end

    def comparable_path_for(path)
      if @options[:ignore_params]
        path.gsub(/\?.*/, '')
      else
        path
      end
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for ["admin", @category] do |f| %>

	<%= error_messages_for @category %>

	<div class="control-group">
		<%= f.label :parent_id %>
		<div class="controls">
			<%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, {:prompt => true} %>			
		</div>
	</div>
	<div class="control-group">
    <%= f.label :name %>
		<div class="controls"></div>
    <%= f.text_field :name %>
  </div>



  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
		<%= link_to 'Back', admin_categories_path, :class => "btn" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<% model_class = Category %>

<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize %></h2>
</div>

<table class="table table-striped">
  <thead>
		<tr>
	    <th><%= model_class.human_attribute_name(:name) %></th>
	    <th><%=t '.actions', :default => t("helpers.actions") %></th>
	  </tr>
	</thead>
	<tbody>
		<% @categories.each do |category| %>
			<tr>
		    <td><%= link_to category.name, admin_category_path(category) %></td>
		    <td><%= link_to 'Edit', edit_admin_category_path(category), :class => "btn btn-mini" %> <%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Category', new_admin_category_path, :class => "btn btn-primary" %>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

app/views/admin/categories/show.html.erb
<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<%= link_to 'Back', admin_categories_path, :class => "btn" %>

app/views/admin/companies/_form.html.erb
<%= form_for ["admin", @company] do |f| %>

	<%= error_messages_for @company %>

	<div class="control-group">
		<%= f.label :category, :class => 'control-label' %>
		<div class="controls">
		  <%= f.select :category_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, {:prompt => true} %>
		</div>
	</div>
	

  <div class="control-group">
		<%= f.label :name %>
		<div class="controls">
    	<%= f.text_field :name, :class => 'span6' %>
  	</div>
	</div>

	<div class="control-group">
    <%= f.label :phone %>
		<div class="controls">
    	<%= f.text_field :phone, :class => "span6" %>
  	</div>
	</div>

  <div class="control-group">
    <%= f.label :address %>
		<div class="controls">
    	<%= f.text_area :address, :class => "span6" %>
  	</div>
	</div>
  <div class="control-group">
    <%= f.label :website %>
		<div class="controls">
    	<%= f.text_field :website, :class => 'input-xxlarge' %>
		</div>
  </div>
  <div class="control-group">
    <%= f.label :email %>
		<div class="controls">
    	<%= f.text_field :email, :class => 'input-xxlarge' %>			
		</div>
  </div>

	<div class="control-group">
		<%= f.label :description %>
		<div class="controls">
    	<%= f.text_area :description, :class => "span6" %>
		</div>
  </div>

	<br/>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
		<%= link_to 'Back', admin_companies_path, :class => "btn" %>
  </div>
<% end %>

<script type="text/javascript">
	jQuery(function($){
	   $("#company_phone").mask("(99) 9999-9999");
	});
	$(function(){
	  $('#company_website').bind('click', function(e){
	    if($.trim($(e.target).val())=='') $(e.target).val('http://');
	  })
	})
	
</script>

app/views/admin/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

app/views/admin/companies/index.html.erb
<% model_class = Company %>

<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize %></h2>
</div>

<table class="table table-striped">
	<thead>
  	<tr>
	    <th><%= model_class.human_attribute_name(:name) %></th>
	    <th><%= model_class.human_attribute_name(:address) %></th>
	    <th><%= model_class.human_attribute_name(:website) %></th>
	    <th><%= model_class.human_attribute_name(:email) %></th>
	    <th><%= model_class.human_attribute_name(:created_at) %></th>
	    <th><%=t '.actions', :default => t("helpers.actions") %></th>
	  </tr>
	</thead>
<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.address %></td>
    <td><%= company.website %></td>
    <td><%= company.email %></td>
		<td><%= company.created_at %></td>
    <td><%= link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_company_path(company), :class => 'btn btn-mini' %></td>
    <td><%= link_to t('.destroy', :default => t("helpers.links.destroy")), admin_company_path(company), :method => :delete,          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },            :class => 'btn btn-mini btn-danger' %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @companies %>

<%= link_to 'Adicionar', new_admin_company_path, :class => "btn btn-primary" %>

app/views/admin/companies/new.html.erb
<h1>New company/Empresa</h1>

<%= render 'form' %>

app/views/admin/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Address:</b>
  <%= @company.address %>
</p>

<p>
  <b>Website:</b>
  <%= @company.website %>
</p>

<p>
  <b>Email:</b>
  <%= @company.email %>
</p>

<p>
  <b>Description:</b>
  <%= @company.description %>
</p>

<p>
  <b>Category:</b>
  <%= @company.category.name %>
</p>


<%= link_to 'Edit', edit_admin_company_path(@company) %> |
<%= link_to 'Back', admin_companies_path %>

app/views/admin/dashboard/index.html.erb
teste

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :address, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :category_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                companies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<div class="span12" >
</div>
<div class="span2">
	<div class="sidebar-nav filters">
		<% if @category_root %>
			<button class="btn btn-large btn-block btn-primary" type="button"><%= @category_root.name %></button>
			<ul class="nav nav-tabs nav-stacked">
				<% @category_root.descendants.each do |category| %>
					<%= nav_link category.name, companies_path(:category_root => @category_root, :category_id => category.id), {:class => ''}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
				<% end %>
			</ul>
		<% end %>
	</div>
</div>
<div class="span8">

  <% @companies.each do |company| %>
	<div class="companies">
		<small><%= link_to company.category.name, companies_path(:category_id => company.category.id) %></small>
		<h3><%= link_to company.name, company_path(company) %> - <i class="icon-phone"> </i> <%= company.phone %></h3>    
	<p class="">
		<%= company.address %>
	</p>
	<div>
		<%= link_to "#", :class => "btn btn-mini" do %>
	   <i class="icon-map-marker"> </i> Como chegar
		<% end %>
		<%= link_to company.website, :class => "btn btn-mini" do %>
			<i class="icon-home icon-white"> </i> Site
		<% end %>
		<%= link_to "#", :class => "btn btn-mini" do %>
		  <i class="icon-envelope"> </i> e-mail
		<% end %>
	</div>
</div>
<hr/>
<% end %>
    
	<%= will_paginate @companies, :previous_label => "<<", :next_label => ">>", :class => "pagination pagination-large"  %>

</div>
<div class="span2">
	<ul class="thumbnails">
	  <li class="span2">
	    <a href="#" class="thumbnail">
	      <img src="assets/nasa_veiculos.png">
	    </a>
	  </li>
	  <li class="span2">
	    <a href="#" class="thumbnail">
	      <img src="assets/jaicar.png">
	    </a>
	  </li>
	  <li class="span2">
	    <a href="#" class="thumbnail">
	      <img src="assets/autoeste.jpeg">
	    </a>
	  </li>
	  <li class="span2">
	    <a href="#" class="thumbnail">
	      <img src="assets/nasa_kia.png">
	    </a>
	  </li>
	</ul>
</div>

app/views/companies/new.html.erb
<% model_class = Company %>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %> <small> <%= @company.name %></small></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @company.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @company.website %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @company.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @company.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @company.category_id %></dd>
</dl>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cartem" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin", :media => "all" %>
    <!-- Javascripts
    ================================================== -->
    <%= javascript_include_tag "application" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>


		<style type="text/css">
			body{ margin-top:60px;}
		</style>
		
  </head>

  <body>



    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
					<%= link_to admin_root_path, :class => "brand" do %>
					  Cartendetudo.com <small>Painel de Controle</small>
					<% end %>
          <div class="container nav-collapse">
            <ul class="nav">
							<%= link_to new_admin_company_path, :class => "btn btn-primary" do %>
							<i class="icon-briefcase icon-white"></i> Adicionar Empresa
							<% end %>
							<%= link_to new_admin_category_path, :class => "btn" do %>
							<i class="icon-flag"></i> Adicionar Categoria
							<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
				<div class="span3 well">
					<ul class="nav nav-list">
						<li class="nav-header">Navegação</li>
						<li class="active"><%= link_to "Início", admin_root_path %></li>
						<li><%= link_to "Empresas", admin_companies_path %></li>
						<li><%= link_to "Categorias", admin_categories_path %></li>
					</ul>
				</div>
        <div class="span9 well main_content">
					<%= flash_messages %>
          <%= yield %>
        </div>
      </div><!--/row-->


			<hr/>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <title>cartendtudo - Automóveis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A cartendtudo tem uma ampla rede de profissionais para atender veículos Nacionais e Importados.">
	<meta name="keywords" content="site, carro, carros, veículo, veículos, automóveis, automóvel, peças, peça, serviços, serviço, mecânica, lanternagem, pintura, eletricista, mecânico, Goiás, Goiânia, Anápolis, pintor, lanterneiro">

  <meta name="author" content="Rogerio Alexandre">

  <!-- Le styles -->

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Le fav and touch icons -->
  <link rel="shortcut icon" href="../assets/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
	<header class="container">

    <!-- Main hero unit for a primary marketing message or call to action -->
		<div class="row">
		  <div class="span4">
		  	<%= link_to root_path do %>
					<h1 class="logomarca">CAR<small>tendetudo.com</small></h1>
				<% end %>
		  </div>
		  <div class="span8" style="margin-top:20px">
		  	<%= image_tag "car_city.png" %>
		  </div>
		</div>

		<div class="container navbar-wrapper">
			<div class="navbar">
			  <div class="navbar-inner">
			    <div class="container">
			      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </a>
      
			      <div class="nav-collapse">
			        <ul class="nav">
								<%= nav_link "Início", root_path, {:class => ''}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
                <% @category_roots.each do |category| %>
									<%= nav_link category.name, companies_path(:category_root => category.id), {:class => ''}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
  							<% end %>
			        </ul>
			      </div><!-- /.nav-collapse -->
			    </div>
			  </div><!-- /navbar-inner -->
			</div><!-- /navbar -->
		</div>

	</header>
	
	<section class="container">
		<div class="row">
		<%= yield %>
		</div>

		<hr/>
    <footer>
      <p>&copy; Rede Car 2012 - Todos os direitos reservados</p>
    </footer>
	
	</section>
	<script type="text/javascript">
	</script>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-error">
    <h4>
      <%= t "error_message_header",
            :count => resource.errors.count,
            :model => resource.class.model_name.human %>      
    </h4>
  </div>
<% end %>